### ISSUE TITLE
Enhancement / [NAME]

### ISSUE THREAD

**Issue by yilinwanglavinia** [UMHelper/Feedback-and-Join-Us#1]
* Client 版本: Web 網頁端/ Wechat 小程序
* Suggestion on which page 希望有新功能的界面: 课程简介/教授简介
* Suggestion desc 功能/改進描述: 很多课程评论数较少or无评论，建议定向incentivize更多人去评论
* I really need it! 需求程度: __5__ / 10

**Comment by BoxMars** [comment]
啊這,教授簡介在做了.
