### ISSUE TITLE
Apply to be a member 申請加入團隊 / Kelvin

### ISSUE THREAD

**Issue by keltam27** [UMHelper/Feedback-and-Join-Us#15]
* I am Kelvin Tam, a year 3 student majoring in Computer Science.
* Having skills in HTML, CSS, PHP (Laravel Framework), MySQL, C#, Wechat Mini program, Design (PS & Ai), Photography, Society Management. 
* Learning Javascript, Andriod Studio.
* Desired team: (Frontend, Backend, UI, or Marketing) To be assigned.
* Email: tamhoichon@gmail.com
* Here is my CV: https://drive.google.com/file/d/1PcUXZCd9w59WFMhU2mEB_OJJb47m5QAh/view?usp=sharing

**Comment by BoxMars** [comment]
Please check your e-mail inbox.
