### ISSUE TITLE
Apply to be a member 申請加入團隊 / [NAME]

### ISSUE THREAD

**Issue by RupertCJZ** [UMHelper/Feedback-and-Join-Us#17]
I am Zhou Jicheng (Rupert), year 4  student majoring in CS at UM.
 I  wanner some experience on managing the project and also learn more.
 Desired team: To be honest, I'm not quite familar with the functionality of these different teams but I might prefer the frontedn and UI 
 team. 
 Email:  db92779@um.edu.mo
 Plz find my CV in the link.
(https://drive.google.com/file/d/14-JPlch2_Suz8dUeNLCnCQipdcxDUcx9/view?ths=true)

**Comment by BoxMars** [comment]
Hi Rupert,

Thanks for submitting your application. Our team will review your resume and reply you ASAP.

Box

**Comment by poplar-xirolan** [comment]
Hello! I have a small question. It seems that you are in year 4 and are going to graduate soon. Can you continue to study in UM after you get your bachelor's degree? If so, it would be of significant help to us since all our team members are going to graduate next year, and may not be able to continue maintaining this project as frequently as before.

**Comment by RupertCJZ** [comment]
I plan to have my master degree in UM.  I think I could help with this project~

**Comment by poplar-xirolan** [comment]
Thanks! After reviewing your application, I personally support your request. Other team members @BoxMars and @stiven-ding will review your request ASAP.

**Comment by RupertCJZ** [comment]
Thank you for your kind attention! It will be a joy for me if I have this chance.

**Comment by BoxMars** [comment]
Do u have some experience in developing web projects or knowledge about this.

**Comment by BoxMars** [comment]
Pls check your inbox ([redacted for privacy] AT [redacted for privacy])

**Comment by RupertCJZ** [comment]
Of course, I have some experience in developing web projects but little for the back-end.

**Comment by BoxMars** [comment]
i can not find any detail about this in you resume

**Comment by RupertCJZ** [comment]
Oh, sorry. Maybe I didn't mention it clealy. I have the experience in creating the web project for my web programming course.
