### ISSUE TITLE
Apply to be a member 申請加入團隊 / [NAME]

### ISSUE THREAD

**Issue by JFungx** [UMHelper/Feedback-and-Join-Us#18]
* I am JFung, first year postgraduate student majoring in internet of thing.
* Having skills in Python, Html, css, Javascript, Mysql, C, Java. 
* Learning Vue and Wechat mini program.
* Desired team: Frontend and UI design.
* Email: db82646@um.edu.mo
* Here is my CV: [(link)](https://bit.ly/3cOqoMp)

**Comment by poplar-xirolan** [comment]
Thanks! After reviewing your application, I think that you are outstanding and is able to maintain all our projects, since their tech stack is the same as what you have mastered. Please wait other 2 members to review.

**Comment by BoxMars** [comment]
Pls check your inbox (db82646 AT um DOT edu DOT mo)

**Comment by JFungx** [comment]
Thank you so much!
