### ISSUE TITLE
Apply to be a member 申請加入團隊 / [NAME]

### ISSUE THREAD

**Issue by MerrryF** [UMHelper/Feedback-and-Join-Us#19]
* I am Fan Xiao Yue (Merry), year 2 student majoring in Computer Science.
* Having skills in Java, C, C++, Python and Facebook/ig page management. 
* Learning: Since I just finished the basic course of CS, my professional abilities are mainly programming skills, and experience in social media page or website management.
* Desired team: UI or Marketing 
* Email: fm.xiaoyue@gmail.com
* Here is my CV: [Fan Xiao Yue_CV.pdf](https://github.com/UMHelper/Feedback-and-Join-Us/files/9230685/Fan.Xiao.Yue_CV.pdf)

**Comment by BoxMars** [comment]
Hi Merry,

Thanks for submitting your application. Our team will review your resume and reply you ASAP.

Box

**Comment by BoxMars** [comment]
Pls check ur email (fm.xiaoyue AT gmail DOT com)
