### ISSUE TITLE
Data issue / Duplicated Comments

### ISSUE THREAD

**Issue by kchomacau** [UMHelper/Feedback-and-Join-Us#2]
* Client 版本: Web 網頁端
* Course Code: GELH1000
* Instructor Name: MA WAN CHAM
* Error type 類型: 重覆的評論 (可能是由於提交頁面的提交按鈕容許雙擊?)

**Comment by poplar-xirolan** [comment]
Thanks for your feedback! We will investigate into this problem as soon as possible.

**Comment by BoxMars** [comment]
已经删除了重复的评论, 后端的提交评论部分也增加了重复性检验. 谢谢
