### ISSUE TITLE
回頂按鈕BUG or 建議

### ISSUE THREAD

**Issue by yyyyyyounger** [UMHelper/Feedback-and-Join-Us#33]
問題描述：回頂按鈕在點擊後不會立即回頂，能感受到明顯的延遲。

復現link：https://www.umeh.top/reviews/ABCD1234/ABC

復現過程：把進度條拉到中間或底部，點擊回頂，應該需要1s左右的時間才能成功回頂。

**Comment by yyyyyyounger** [comment]
手機版和電腦版均出現該種情況。

**Comment by stiven-ding** [comment]
CF plugin bug

**Comment by stiven-ding** [comment]
CF plugin function deprecated.
